### ISSUE TITLE
View Category List Request

### ISSUE THREAD

**Issue by alexsendre** [alexsendre/Pelicans-RarePublishingAPI#12]
# User Story
Given a user selects the "Category Management" from the navbar
When they are directed to /categories
Then they should see a list of all categories
And categories should be ordered alphabetically
And each category should have an edit and delete button (functionality for buttons come later)

# Dev Notes
this will be a GET request that will return a table of alphabetically sorted list of categories. 

example: 
```
app.MapGet("/customers", () =>
{
    return customers;
});
```

the URL for this request will be `/categories`

**Comment by ndswimming92** [comment]
Created endpoint that sorts categories alphabetically:

```
app.MapGet("/categories", () =>
{
    var sortedCategories = categories.OrderBy(c => c.Label).ToList();
    return sortedCategories;
});
```
