### ISSUE TITLE
Create a Category

### ISSUE THREAD

**Issue by Bonni535** [alexsendre/Pelicans-RarePublishingAPI#15]
# User Story

As a User I would like to be able to create new Categories
Given a User is on the Category list page
When they select the Create Category button
Then they should be directed to a form in which they can enter a new category name
Given a User has entered a Category name
When they click the Save button
Then a new category should be saved to the database
And the User should be directed to the Category list page and see the new Category that has been added

# Dev Notes

This will be a POST request.

Example:
```
app.MapPost("/api/tickets", (ServiceTicket serviceTicket) =>
{
    serviceTicket.Id = serviceTickets.Max(st => st.Id) + 1;
    serviceTickets.Add(serviceTicket);
    return serviceTicket;
});
```
The URL for this request will be `/api/categories`

**Comment by ndswimming92** [comment]
Created a new category endpoint:

```
app.MapPost("/newCategories", (Categories category) =>
{
    category.Id = categories.Max(c => c.Id) + 1;
    categories.Add(category);
    return category;
});
```
