### ISSUE TITLE
Filter post list by category

### ISSUE THREAD

**Issue by Bonni535** [alexsendre/Pelicans-RarePublishingAPI#21]
# User Story

As a user I would like to be able to filter all posts by category.
# Acceptance Criteria

When a category is selected, only the post that have that tag should show.

# Dev Notes

An endpoint that allows to filter the posts by categories should be created

**Comment by ndswimming92** [comment]
Created an endpoint that allows to filter the posts by categories

```
app.MapGet("/postsByCategory/{categoryId}", ( int categoryId) =>
{
    var filteredPosts = posts.Where(p => p.CategoryId == categoryId).ToList();
    if (filteredPosts.Count == 0)
    {
        return Results.NotFound();
    }
    return Results.Ok(filteredPosts);
});
```
