### ISSUE TITLE
Class Models

### ISSUE THREAD

**Issue by alexsendre** [alexsendre/Pelicans-RarePublishingAPI#23]
Define Classes for the following: 
- [x] Users
- [x] Posts
- [x] Comments
- [x] Tags
- [x] Post Tags
- [x] Subscriptions
- [x] Reactions
- [x] Post Reactions
- [x] Categories

These classes will each have their own .cs file with their respective name. 

All of these files will be located inside the `Models` folder

**Comment by B33blebroxx** [comment]
Subscriptions and posts

**Comment by ndswimming92** [comment]
I'll take Users and Categories.

**Comment by Bonni535** [comment]
Tags and Post tags

**Comment by alexsendre** [comment]
I will be handling comments, reactions & post reactions
